name: Metrics
env:
  GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
on:
  # Her gece 03:00'te çalış
  schedule: [{cron: "0 0 * * *"}]
  # Elle tetiklemek istersen
  workflow_dispatch:
  # Repoya bir şey yüklediğinde çalış
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. GÖREV: AYDINLIK MOD (Light)
      - name: Light Mode Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: icons/github-metrics-light.svg
          user: onder-akkaya
          template: classic
          base: "" 
          config_timezone: Europe/Istanbul
          config_theme: light
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%

      # 2. GÖREV: KARANLIK MOD (Dark)
      - name: Dark Mode Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: icons/github-metrics-dark.svg
          user: onder-akkaya
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          config_theme: dark
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
