name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. GÖREV: AYDINLIK MOD (Vercel Light Tarzı)
      - name: Light Mode Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: icons/github-metrics-light.svg
          user: onder-akkaya
          template: classic
          base: "" 
          config_timezone: Europe/Istanbul
          
          # --- GÖRÜNÜM AYARLARI ---
          config_theme: light
          config_padding: 6% # Kartın kenar boşlukları (Vercel havası için)
          config_display: regular # Kartın boyutu
          
          # --- DİL AYARLARI ---
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          plugin_languages_chart: false # Pasta grafik KAPALI
          plugin_languages_details: percentage # Sadece yüzde (Satır sayısı yok)

      # 2. GÖREV: KARANLIK MOD (Vercel Dark Tarzı)
      - name: Dark Mode Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: icons/github-metrics-dark.svg
          user: onder-akkaya
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          
          # --- GÖRÜNÜM AYARLARI ---
          config_theme: dark
          config_padding: 6%
          config_display: regular
          
          # --- DİL AYARLARI ---
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          plugin_languages_chart: false
          plugin_languages_details: percentage
