name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. AYDINLIK MOD (Temiz, Beyaz Kart, Pasta Grafik)
      - name: Light Mode Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: icons/github-metrics-light.svg
          user: onder-akkaya
          template: classic
          base: "" 
          config_timezone: Europe/Istanbul
          
          # Görünüm
          config_theme: light
          config_padding: 10%
          config_display: regular
          
          # Dil Ayarları (Pasta Grafik Geri Geldi - Çünkü Bar Modu İğrenç)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          # Burası Önemli: Pasta grafiği açtık ki o saçma çizgi gitsin
          plugin_languages_chart: true 
          plugin_languages_details: percentage

      # 2. KARANLIK MOD (Siyah Kart, Pasta Grafik)
      - name: Dark Mode Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: icons/github-metrics-dark.svg
          user: onder-akkaya
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          
          config_theme: dark
          config_padding: 10%
          config_display: regular
          
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          plugin_languages_chart: true
          plugin_languages_details: percentage
